ProjetoFinalDj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('monte_seu_time/', include('monte_seu_time.urls')),
    path('campeonatos/', include('campeonatos.urls')),
    path('partidas/', include('partidas.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('admin/', admin.site.urls)
]

autenticacao/urls.py
from django.urls import path
from autenticacao import views

app_name = 'autenticacao'

urlpatterns = [
    path('', views.autenticacao, name = 'home'),
    path('login/', views.login, name = 'login'),
    path('cadastro/', views.cadastro, name = 'cadastro'),
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name = 'home')
]

autenticacao/models.py
from django.db import models

# Create your models here.

autenticacao/views.py
from django.shortcuts import render

def autenticacao(request):
    return render(request, 'autenticacao/login.html')

def login(request):
    return render(
        request,
        'autenticacao/login.html',
        {
            'title': '| Login',
        }
    )

def cadastro(request):
    return render(
        request,
        'autenticacao/cadastro.html',
        {
            'title': '| Cadastro',
        }
    )

autenticacao/templates/autenticacao/cadastro.html
{% extends "global/partials/autenticacao.html" %}

{% block title %}{{title}}{% endblock title %}

{% block id %}
    formCadastro
{% endblock id %}

{% block content %}
    <form action="">
        <div class="m-3">
            <label for="email" class="form-label fw-bold">E-mail</label>
            <input type="email" id="email" class="form-control" required>
        </div>
        <div class="m-3">
            <label for="nome" class="form-label fw-bold">Nome do usuário</label>
            <input type="text" id="nome" class="form-control" required>
        </div>
        <div class="m-3">
            <label for="senha" class="form-label fw-bold">Senha</label>
            <input type="password" id="senha" class="form-control" required>
        </div>
        <div class="m-3">
            <label for="senha" class="form-label fw-bold">Confirme sua senha</label>
            <input type="password" id="senha" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-dark mb-2">Cadastrar</button>
        <span class="linha"></span>
        <h6 class="mb-3 fw-bold">Já tem conta?<a href="{% url "autenticacao:login" %}" class="login m-1">Login</a></h6>
    </form>
{% endblock content %}

autenticacao/templates/autenticacao/login.html
{% extends "global/partials/autenticacao.html" %}

{% block title %}{{title}}{% endblock title %}

{% block id %}
    formLogin
{% endblock id %}

{% block content %}
    <form action="">
        <div class="m-3">
            <label for="email" class="form-label fw-bold">E-mail</label>
            <input type="email" placeholder="Seu e-mail" id="email" class="form-control" required>
        </div>
        <div class="m-3">
            <label for="senha" class="form-label fw-bold">Senha</label>
            <input type="password" id="senha" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-dark mb-2">Login</button>
        <span class="linha"></span>
        <h6 class="mb-3 fw-bold">Não tem uma conta?<a href="{% url "autenticacao:cadastro" %}" class="cadastro m-1">Criar conta</a></h6>
    </form>
{% endblock content %}